### ISSUE TITLE
Unknown Error - There was an error communicating with the service.  Fout-ID: c6a52170

### ISSUE THREAD

**Issue by Poetszorg** [Gladior-B-V/afas-profit-connector#1]
I am getting the following error in Google Lookerstudio with my afas profit connector.

![image](https://user-images.githubusercontent.com/122869929/226704650-fb3b1cf8-161e-4579-840b-6f8b28e3c729.png)

**Comment by zoedufrenne** [comment]
Hi @Poetszorg, Yesterday we did an update of the data hub. The connector is working again. Thanks for letting us know!
