### ISSUE TITLE
not read data source

### ISSUE THREAD

**Issue by Hamed208** [Gladior-B-V/afas-profit-connector#2]
Hi, I had  dashboard from AFAS in Looker by help of Gladior connector,  but I just change in step 3  AFAS Profit connector to  to see what will happen but when I back again to right profit connector the data source doesn't read  and also  "click to connect to continue" is not active. Just I can see on the top right  "reconnection" but after press that one, is not able to read the data source and dashabord is stop to working.   I would appreciate your comments and help for this isuue.

Regards,
Hamed

**Comment by rkooiker** [comment]
Hi @Hamed208, could you please provide your Data hub user ID? This is found under your profile -> edit profile, and is the grayed out number on the bottom of the pop-up. Some screenshots of the issue would also be greatly appreciated.
